name: Deploy su cPanel

on:
  push:
    branches:
      - main



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installa dipendenze React
        run: |
          cd simplyai-FE
          npm install

      - name: Build React
        run: |
          cd simplyai-FE
          npm run build
        env:
          CI: false

      # FRONTEND - carica dist/ nella root di clearplanai.it
      - name: Deploy Frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          local-dir: simplyai-FE/dist/
          server-dir: /
          dangerous-clean-slate: false

      # BACKEND - carica simplyai-BE/ nella cartella backend
      - name: Deploy Backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER_BE }}
          password: ${{ secrets.FTP_PASS_BE }}
          port: 21
          local-dir: simplyai-BE/
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
